<div align="center">

# Avanindra Vijay

**AI Engineer · GenAI Developer · Data Scientist**

Building practical AI systems — LLMs, RAG, Agentic AI, Computer Vision

[![GitHub](https://img.shields.io/badge/GitHub-111111?style=for-the-badge&logo=github&logoColor=white)](https://github.com/AvanindraVijay)
[![LinkedIn](https://img.shields.io/badge/LinkedIn-111111?style=for-the-badge&logo=linkedin&logoColor=white)](https://www.linkedin.com/in/vijayavanindra/)
[![Portfolio](https://img.shields.io/badge/Portfolio-111111?style=for-the-badge&logo=googlechrome&logoColor=white)](https://portfolio-ga9f.onrender.com/)

</div>

---

## About

I build practical AI systems around Generative AI, LLMs, RAG, Agentic AI, and Computer Vision.

My work focuses on turning AI models into usable software through Python, FastAPI, PostgreSQL, vector search, APIs, and cloud-native deployment.

---

## Engineering Stack

**AI / ML**
`Generative AI` `LLMs` `RAG` `LangChain` `LangGraph` `Transformers` `NLP` `Computer Vision` `YOLO` `OCR`

**Backend / Data**
`Python` `FastAPI` `PostgreSQL` `FAISS` `BM25` `Pandas` `Plotly` `REST APIs`

**Cloud / DevOps**
`Docker` `Kubernetes` `Azure` `Git` `GitHub`

---

## Selected Work

**AI-Powered Inspection System**
Computer vision system that analyzes mechanic-uploaded images and compares detected lift components against expected order/BOM data.
Detection: YOLO, OCR, Image Matching · Backend: FastAPI, PostgreSQL · Interface: Microsoft Power Apps

**RAG & Agentic AI Systems**
Context-aware AI applications built with retrieval pipelines, vector search, conversational memory, and graph-based workflows.
Stack: LangChain, LangGraph, FAISS, BM25, PostgreSQL, Local LLMs

**Natural Language → SQL**
AI-powered analytics system that converts natural-language questions into validated, executable PostgreSQL queries.
Stack: LLM, RAG, PostgreSQL, FastAPI, Plotly

---

## AI Architecture

```
                    USER
                      |
                      v
              +---------------+
              |   AI API      |
              |   FastAPI     |
              +-------+-------+
                      |
          +-----------+-----------+
          v           v           v
        RAG        AGENTS      VISION
          |           |           |
          v           v           v
      Vector DB   LangGraph      YOLO
          |           |           |
          +-----------+-----------+
                      v
                     LLM
                      |
                      v
                AI RESPONSE
```

---

## GitHub Activity

<div align="center">
<img src="https://github-readme-stats.vercel.app/api/pin/?username=AvanindraVijay&repo=AvanindraVijay" width="90%">
</div>

*Note: the public `github-readme-activity-graph.vercel.app` instance is currently over its free quota (returns HTTP 402) and can't render. Options: self-host it (fork `Ashutosh00710/github-readme-activity-graph`, deploy your own Vercel project, swap the domain below), or drop this widget. Once you have your own domain, restore it as:*
```
![Activity Graph](https://YOUR-OWN-DEPLOYMENT.vercel.app/graph?username=AvanindraVijay&bg_color=0d1117&color=8b949e&line=58a6ff&point=ffffff&area=true&hide_border=true)
```

---

## 3D Contribution Graph

<div align="center">
<img src="./profile-3d-contrib/profile-night-rainbow.svg" width="95%" alt="3D GitHub contribution graph">
</div>

*This image is generated by the workflow file below — it won't appear until the Action has run at least once.*

---

## Stats

<div align="center">
<img src="https://github-readme-stats.vercel.app/api?username=AvanindraVijay&show_icons=true&hide_border=true&bg_color=0d1117&title_color=ffffff&text_color=8b9498&icon_color=58a6ff" width="48%">
</div>

---

## Currently Exploring

`Multimodal LLMs` `Agentic AI` `LLM Optimization` `Computer Vision` `Kubernetes` `Cloud AI`

---

<div align="center">

**Build · Learn · Ship**

</div>
